name: Build

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      pull-requests: write

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        dotnet: 
          - '6.0.x'
          - '7.0.x'

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - run: dotnet restore

    - run: dotnet build src/Helmet.csproj --no-restore

    - run: dotnet test

    - run: dotnet pack src/Helmet.csproj --no-build --output .
